- name: Install git yum
  yum: name=git state=latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Amazon'      

- name: Install git apt
  apt: name=git update_cache=yes
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
