---
# tasks file for base

# register_vars [TODO]

- include: register_vars.yml

- include: clean_package.yml
  when: ( ansible_os_family|lower == 'debian' )

- include: upgrade_distro.yml

- include: swap.yml

- include: timezone.yml

- include: locales.yml

- include: authorized_keys.yml
  tags: ['ssh']
- include: sshlog.yml
  when: sshlog|bool == True 
- include: git.yml


- include: reboot_if_needed.yml


