- name: upgrade all packages debian
  apt:
    upgrade: dist
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'


- name: upgrade all packages centos
  yum:
    name: '*'
    state: latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Amazon'


